
addons:
  apt:
    update: true
    packages:
    - cppcheck
    - valgrind
    - cmake
    - libgtest-dev
    - lcov

language: cpp

before_install:
# Установка gtest
- cd /usr/src/gtest 
- sudo cmake CMakeLists.txt || (cat CMakeFiles/CMakeError.log && CMakeFiles/CMakeOutput.log)
- sudo make
- sudo cp *.a /usr/lib
- cd -

before_script:
- cd PT2
- cmake CMakeLists.txt
- make
- ls
    
jobs:
  include:
    - stage: "cppcheck"
      script: cppcheck -j4 --inconclusive --error-exitcode=1 --language=c *.c *.h
      
    - stage: "memcheck"
      script:
      - python3 create_test.py 
      - valgrind --error-exitcode=1 --leak-check=full -q ./PersTask2 <test.txt
      - valgrind --error-exitcode=1 --leak-check=full -q ./ParallelPersTask2 <test.txt
      - rm test.txt

    - stage: "stresstest"
      script:
      - python3 create_test_file.py
      - ./PersTask2 <test.txt
      - ./ParallelPersTask2 <test.txt
      - rm test.txt
      
    - stage: "gtest"
      script: 
      - ./tests_gtest
      - ./parallel_tests_gtest
      after_success:
      - lcov --directory . --capture --output-file coverage.info
      - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
      - lcov --list coverage.info
      - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
      
after_script: make clean
